### ISSUE TITLE
Feature: Grading System

### ISSUE THREAD

**Issue by ThijsvanDijk** [ApericotStudio/Poltergeist#161]
Criteria:
- [x] The end of level screen needs to show the grade you got for your geisting performance
- [x] Ask designer what variables influence the grade and how much
- [x] Keep track of these variables and show them in the end screen for the level
- [ ] Level end screen should include three buttons: "Resit" (Restart), Next assignment (Next level) and Level Select 
- [x] Best grade achieved (with the tracked variables) per level should be saved.

**Comment by Jeroenvn** [comment]
I've asked the designers what variables influence the grade in the design-chat on discord
