### ISSUE TITLE
Feat: Rig the UI up with code

### ISSUE THREAD

**Issue by Jeroenvn** [ApericotStudio/Poltergeist#255]
Make Elizes UI functional and integrate it into our game

Functional:
- [x] Options
- [x] Pause
- [x] Results (End Game)
- [x] Quit Confirmation
- [x] Tutorial Textbox
- [x] Main Menu
- [x] Level Select
- [x] Overlay (In Game)
- [x] Credits
- [x] Intro

Integrated:
- [x] Options
- [x] Pause
- [x] Results (End Game)
- [x] Quit Confirmation
- [x] Tutorial Textbox
- [x] Main Menu
- [x] Level Select
- [x] Overlay (In Game)
- [x] Credits
- [x] Intro

**Comment by ThijsvanDijk** [comment]
Everything done, very nice!
