### ISSUE TITLE
Change: Dani Bugs

### ISSUE THREAD

**Issue by ThijsvanDijk** [ApericotStudio/Poltergeist#270]
List:
- [x] Shovel mass to 2.5
- [x] Throwables do no fear
- [x] Outline widths to 7.5
- [x] Sink has no collision
- [x] Bathroom walls make you go into first-person
- [x] Visitor room roam time to 30 seconds
- [x] More things to look at in hallway
- [x] Piano and Lawnmower to medium scare (balancing)
- [x] Update lantern models in courtyard
- [x] Broken objects despawn
- [x] Make "look at object" time variable for visitors
- [ ] Visitor voice line is cut off when running out of the house
- [x] Visitors are immune against scares while investigating
- [x] Remove interactables that dont do anything
- [x] Update bathroom walls

**Comment by UpperCi** [comment]
Room roam time should be 30 seconds, not 50!

**Comment by ThijsvanDijk** [comment]
There is no non-hacky way to make the voice lines not cut off, so im closing the issue as others are done
