### ISSUE TITLE
Fix: NPC not following room structure (IMPORTANT)

### ISSUE THREAD

**Issue by ThijsvanDijk** [ApericotStudio/Poltergeist#373]
Ask Lucas for more clarification

**Comment by UpperCi** [comment]
Visitor roams the expected amount of time in the first room. After that, it will 'choose' a new room every 5 seconds, regardless of what it's currently doing. This even leads to them skipping rooms if they have to walk a long distance.

**Comment by UpperCi** [comment]
Maybe found the problem? In `NPC/States/RoamState.cs`, the `Handle()` function calls `PeriodicallySwitchRoomCoroutine()`. This function contains asynchronously switches rooms. Could it be that this gets called whenever the visitor changes state, e.g. by looking at a new object?

**Comment by KiwiLT** [comment]
Dani hit the nail on the head with his theory. A switchroom coroutine was started each time the npc went to roam state, which equals each time they look at an object.
