### ISSUE TITLE
Change: Lucas & Dani Parameter List

### ISSUE THREAD

**Issue by ThijsvanDijk** [ApericotStudio/Poltergeist#379]
Criteria
Visitor:
- Roaming Speed: 2
- Panicked Speed: 7
- Investigating Speed: 1.7
- Investigate Time: 2
- Time spend in room: 30

Realtor:
- Roaming Speed: 2.5
- Investigating Speed: 3
- Investigate Time: 1

**Comment by UpperCi** [comment]
https://github.com/ApericotStudio/Poltergeist/pull/382
