### ISSUE TITLE
fix: arc still visible when in air and clicking mouse button

### ISSUE THREAD

**Issue by hassanmohamed2003** [ApericotStudio/Poltergeist#86]
![image](https://github.com/ApericotStudio/Poltergeist/assets/93173945/4817ed7b-681b-461e-a590-20fc3d32aeda)

**Comment by Jeroenvn** [comment]
https://github.com/ApericotStudio/Poltergeist/assets/50752585/99be7326-5178-4d0c-acba-e33ba50d1ce2

Ik heb er nog wat verder naar gekeken. De arc wordt visible omdat throwmode true is maar hij wordt niet geupdate omdat dat afhangt van of de aimmode true is. Wanneer je left mouse button klikt probeert hij wel de aimmode in te gaan met EnterAimMode() maar dat gebeurt dus niet.
