### ISSUE TITLE
feat: interactables kitchen

### ISSUE THREAD

**Issue by hassanmohamed2003** [ApericotStudio/Poltergeist#99]
![image](https://github.com/ApericotStudio/Poltergeist/assets/93173945/eb0c6c21-26c5-40bb-8253-38b3dd48cc96)
![image](https://github.com/ApericotStudio/Poltergeist/assets/93173945/ead175d4-9a16-444f-b9f0-c322a0848c5e)

**Comment by hassanmohamed2003** [comment]
these interactables are not a priority for this week

**Comment by hassanmohamed2003** [comment]
![image](https://github.com/ApericotStudio/Poltergeist/assets/93173945/9d8b3703-3c48-449c-898b-2f84ad272abd)
![image](https://github.com/ApericotStudio/Poltergeist/assets/93173945/32609c8e-2fed-4c8a-bf29-c0a14e258dcc)

**Comment by ThijsvanDijk** [comment]
There is a new issue for this
